#!/bin/bash

export LANG=en_US.UTF-8

sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
service mysql start
/usr/bin/mysql -uroot -p123456 -e 'CREATE DATABASE IF NOT EXISTS ipm'
/usr/bin/mysql -uroot -p123456 ipm < /usr/local/var/ipm_table.sql 
/usr/bin/mysql -uroot -p123456 ipm < /usr/local/var/ip_cn.sql 
/usr/bin/mysql -uroot -p123456 ipm < /usr/local/var/ipm_proto_plan.sql 
/usr/bin/mysql -uroot -p123456 ipm < /usr/local/var/ipm_public_proto_plan.sql
/usr/bin/mysql -uroot -p123456 ipm < /usr/local/var/ipm_data.sql

cd /opt
tar -zxf node-v8.11.1-linux-x64.tar.gz -C /opt
cd /usr/local/bin
ln -sf /opt/node-v8.11.1-linux-x64/lib/node_modules/npm/node_modules/highcharts-export-server/bin/cli.js highcharts-export-server
ln -sf /opt/node-v8.11.1-linux-x64/bin/node node
ln -sf /opt/node-v8.11.1-linux-x64/bin/npm npm
fc-cache -fv
